// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import endpoints_terrariumai_environment "github.com/terrariumai/simulation/pkg/api/environment"
import mock "github.com/stretchr/testify/mock"

// PubsubAccessLayer is an autogenerated mock type for the PubsubAccessLayer type
type PubsubAccessLayer struct {
	mock.Mock
}

// BatchPublish provides a mock function with given fields:
func (_m *PubsubAccessLayer) BatchPublish() {
	_m.Called()
}

// PublishMessage provides a mock function with given fields: channel, message
func (_m *PubsubAccessLayer) PublishMessage(channel string, message interface{}) error {
	ret := _m.Called(channel, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(channel, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueuePublishEvent provides a mock function with given fields: eventName, entity
func (_m *PubsubAccessLayer) QueuePublishEvent(eventName string, entity endpoints_terrariumai_environment.Entity) error {
	ret := _m.Called(eventName, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, endpoints_terrariumai_environment.Entity) error); ok {
		r0 = rf(eventName, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
