// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vec2 struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec2) Reset()         { *m = Vec2{} }
func (m *Vec2) String() string { return proto.CompactTextString(m) }
func (*Vec2) ProtoMessage()    {}
func (*Vec2) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{0}
}

func (m *Vec2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec2.Unmarshal(m, b)
}
func (m *Vec2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec2.Marshal(b, m, deterministic)
}
func (m *Vec2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec2.Merge(m, src)
}
func (m *Vec2) XXX_Size() int {
	return xxx_messageInfo_Vec2.Size(m)
}
func (m *Vec2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec2.DiscardUnknown(m)
}

var xxx_messageInfo_Vec2 proto.InternalMessageInfo

func (m *Vec2) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vec2) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// Taks we have to do
type Entity struct {
	// Unique integer identifier of the agent
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Entity stats
	Class  string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Pos    *Vec2  `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Energy int32  `protobuf:"varint,4,opt,name=energy,proto3" json:"energy,omitempty"`
	Health int32  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	// Owner details
	OwnerUID             string   `protobuf:"bytes,6,opt,name=ownerUID,proto3" json:"ownerUID,omitempty"`
	ModelName            string   `protobuf:"bytes,7,opt,name=modelName,proto3" json:"modelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{1}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Entity) GetPos() *Vec2 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Entity) GetEnergy() int32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Entity) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Entity) GetOwnerUID() string {
	if m != nil {
		return m.OwnerUID
	}
	return ""
}

func (m *Entity) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

// ----------------------
// -- Agent
// ----------------------
// Request data to create new agent
type CreateEntityRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// agent
	Agent                *Entity  `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityRequest) Reset()         { *m = CreateEntityRequest{} }
func (m *CreateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntityRequest) ProtoMessage()    {}
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{2}
}

func (m *CreateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityRequest.Unmarshal(m, b)
}
func (m *CreateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityRequest.Merge(m, src)
}
func (m *CreateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntityRequest.Size(m)
}
func (m *CreateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityRequest proto.InternalMessageInfo

func (m *CreateEntityRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateEntityRequest) GetAgent() *Entity {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Contains data of created agent
type CreateEntityResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// ID of created agent
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityResponse) Reset()         { *m = CreateEntityResponse{} }
func (m *CreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEntityResponse) ProtoMessage()    {}
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{3}
}

func (m *CreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityResponse.Unmarshal(m, b)
}
func (m *CreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *CreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityResponse.Merge(m, src)
}
func (m *CreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEntityResponse.Size(m)
}
func (m *CreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityResponse proto.InternalMessageInfo

func (m *CreateEntityResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateEntityResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request data to delete agent
type DeleteEntityRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Unique integer identifier of the agent to delete
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityRequest) Reset()         { *m = DeleteEntityRequest{} }
func (m *DeleteEntityRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityRequest) ProtoMessage()    {}
func (*DeleteEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{4}
}

func (m *DeleteEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityRequest.Unmarshal(m, b)
}
func (m *DeleteEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityRequest.Merge(m, src)
}
func (m *DeleteEntityRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityRequest.Size(m)
}
func (m *DeleteEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityRequest proto.InternalMessageInfo

func (m *DeleteEntityRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteEntityRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains status of delete operation
type DeleteEntityResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Contains number of entities have beed deleted
	// Equals 1 in case of successful delete
	Deleted              int64    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityResponse) Reset()         { *m = DeleteEntityResponse{} }
func (m *DeleteEntityResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityResponse) ProtoMessage()    {}
func (*DeleteEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{5}
}

func (m *DeleteEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityResponse.Unmarshal(m, b)
}
func (m *DeleteEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityResponse.Merge(m, src)
}
func (m *DeleteEntityResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityResponse.Size(m)
}
func (m *DeleteEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityResponse proto.InternalMessageInfo

func (m *DeleteEntityResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteEntityResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ExecuteEntityActionRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Id for the agent that should perform the action
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// identifier for the action
	// 0: MOVE
	// 1: EAT
	Action uint32 `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	// direction to perform the action in
	// 0: UP
	// 1: DOWN
	// 2: LEFT
	// 3: RIGHT
	Direction            uint32   `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteEntityActionRequest) Reset()         { *m = ExecuteEntityActionRequest{} }
func (m *ExecuteEntityActionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteEntityActionRequest) ProtoMessage()    {}
func (*ExecuteEntityActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{6}
}

func (m *ExecuteEntityActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteEntityActionRequest.Unmarshal(m, b)
}
func (m *ExecuteEntityActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteEntityActionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteEntityActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteEntityActionRequest.Merge(m, src)
}
func (m *ExecuteEntityActionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteEntityActionRequest.Size(m)
}
func (m *ExecuteEntityActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteEntityActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteEntityActionRequest proto.InternalMessageInfo

func (m *ExecuteEntityActionRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ExecuteEntityActionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExecuteEntityActionRequest) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ExecuteEntityActionRequest) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type ExecuteEntityActionResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Was the agent able to perform the action
	WasSuccessful        bool     `protobuf:"varint,3,opt,name=wasSuccessful,proto3" json:"wasSuccessful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteEntityActionResponse) Reset()         { *m = ExecuteEntityActionResponse{} }
func (m *ExecuteEntityActionResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteEntityActionResponse) ProtoMessage()    {}
func (*ExecuteEntityActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{7}
}

func (m *ExecuteEntityActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteEntityActionResponse.Unmarshal(m, b)
}
func (m *ExecuteEntityActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteEntityActionResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteEntityActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteEntityActionResponse.Merge(m, src)
}
func (m *ExecuteEntityActionResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteEntityActionResponse.Size(m)
}
func (m *ExecuteEntityActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteEntityActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteEntityActionResponse proto.InternalMessageInfo

func (m *ExecuteEntityActionResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ExecuteEntityActionResponse) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

type ResetWorldRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetWorldRequest) Reset()         { *m = ResetWorldRequest{} }
func (m *ResetWorldRequest) String() string { return proto.CompactTextString(m) }
func (*ResetWorldRequest) ProtoMessage()    {}
func (*ResetWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{8}
}

func (m *ResetWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetWorldRequest.Unmarshal(m, b)
}
func (m *ResetWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetWorldRequest.Marshal(b, m, deterministic)
}
func (m *ResetWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetWorldRequest.Merge(m, src)
}
func (m *ResetWorldRequest) XXX_Size() int {
	return xxx_messageInfo_ResetWorldRequest.Size(m)
}
func (m *ResetWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetWorldRequest proto.InternalMessageInfo

func (m *ResetWorldRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ResetWorldResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetWorldResponse) Reset()         { *m = ResetWorldResponse{} }
func (m *ResetWorldResponse) String() string { return proto.CompactTextString(m) }
func (*ResetWorldResponse) ProtoMessage()    {}
func (*ResetWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{9}
}

func (m *ResetWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetWorldResponse.Unmarshal(m, b)
}
func (m *ResetWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetWorldResponse.Marshal(b, m, deterministic)
}
func (m *ResetWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetWorldResponse.Merge(m, src)
}
func (m *ResetWorldResponse) XXX_Size() int {
	return xxx_messageInfo_ResetWorldResponse.Size(m)
}
func (m *ResetWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetWorldResponse proto.InternalMessageInfo

// ----------------------
// -- Generic Entity
// ----------------------
// Request data to read entity
type GetEntityRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Unique integer identifier of the agent
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityRequest) Reset()         { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()    {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{10}
}

func (m *GetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityRequest.Unmarshal(m, b)
}
func (m *GetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityRequest.Marshal(b, m, deterministic)
}
func (m *GetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityRequest.Merge(m, src)
}
func (m *GetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntityRequest.Size(m)
}
func (m *GetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityRequest proto.InternalMessageInfo

func (m *GetEntityRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetEntityRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains entity data specified in by ID request
type GetEntityResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Task entity read by ID
	Entity               *Entity  `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityResponse) Reset()         { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()    {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17d1085a606d9278, []int{11}
}

func (m *GetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityResponse.Unmarshal(m, b)
}
func (m *GetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityResponse.Marshal(b, m, deterministic)
}
func (m *GetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityResponse.Merge(m, src)
}
func (m *GetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntityResponse.Size(m)
}
func (m *GetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityResponse proto.InternalMessageInfo

func (m *GetEntityResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*Vec2)(nil), "v1.Vec2")
	proto.RegisterType((*Entity)(nil), "v1.Entity")
	proto.RegisterType((*CreateEntityRequest)(nil), "v1.CreateEntityRequest")
	proto.RegisterType((*CreateEntityResponse)(nil), "v1.CreateEntityResponse")
	proto.RegisterType((*DeleteEntityRequest)(nil), "v1.DeleteEntityRequest")
	proto.RegisterType((*DeleteEntityResponse)(nil), "v1.DeleteEntityResponse")
	proto.RegisterType((*ExecuteEntityActionRequest)(nil), "v1.ExecuteEntityActionRequest")
	proto.RegisterType((*ExecuteEntityActionResponse)(nil), "v1.ExecuteEntityActionResponse")
	proto.RegisterType((*ResetWorldRequest)(nil), "v1.ResetWorldRequest")
	proto.RegisterType((*ResetWorldResponse)(nil), "v1.ResetWorldResponse")
	proto.RegisterType((*GetEntityRequest)(nil), "v1.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "v1.GetEntityResponse")
}

func init() { proto.RegisterFile("simulation-service.proto", fileDescriptor_17d1085a606d9278) }

var fileDescriptor_17d1085a606d9278 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0x93, 0xdd, 0xec, 0xe6, 0x74, 0xbb, 0x24, 0x93, 0xb0, 0x35, 0xa6, 0x02, 0xcb, 0x02,
	0xa9, 0x44, 0x6c, 0xdc, 0x84, 0x48, 0xa0, 0x70, 0x43, 0x4b, 0x2b, 0xb4, 0x37, 0x48, 0xf5, 0xaa,
	0x54, 0xbd, 0x9c, 0xda, 0x07, 0x7b, 0x2a, 0xc7, 0xe3, 0xce, 0x8c, 0xf3, 0x03, 0xe2, 0x86, 0x47,
	0x80, 0x3b, 0x9e, 0x83, 0x37, 0xe1, 0x8e, 0x0b, 0xc4, 0x05, 0x0f, 0x82, 0x66, 0xec, 0xfc, 0x27,
	0x82, 0x5e, 0x25, 0xe7, 0x9c, 0xef, 0xfb, 0xce, 0x9c, 0x39, 0x9f, 0x6d, 0xb0, 0x25, 0x9b, 0x14,
	0x29, 0x55, 0x8c, 0x67, 0xd7, 0x12, 0xc5, 0x94, 0x85, 0xd8, 0xcf, 0x05, 0x57, 0x9c, 0xd4, 0xa6,
	0x03, 0xe7, 0x7e, 0xcc, 0x79, 0x9c, 0xa2, 0x4f, 0x73, 0xe6, 0xd3, 0x2c, 0xe3, 0xca, 0x00, 0x65,
	0x89, 0x70, 0x3e, 0x35, 0x3f, 0xe1, 0x75, 0x8c, 0xd9, 0xb5, 0x9c, 0xd1, 0x38, 0x46, 0xe1, 0xf3,
	0xdc, 0x20, 0xf6, 0xd1, 0x9e, 0x07, 0x27, 0xdf, 0x61, 0x38, 0x24, 0x17, 0x60, 0xcd, 0x6d, 0xcb,
	0xb5, 0x1e, 0x9c, 0x06, 0xd6, 0x5c, 0x47, 0x0b, 0xbb, 0x56, 0x46, 0x0b, 0xef, 0x77, 0x0b, 0x1a,
	0x4f, 0x33, 0xc5, 0xd4, 0x82, 0x5c, 0x42, 0x8d, 0x45, 0x06, 0x57, 0x0f, 0x6a, 0x2c, 0x22, 0x5d,
	0x38, 0x0d, 0x53, 0x2a, 0xa5, 0x01, 0x37, 0x83, 0x32, 0x20, 0x0e, 0xd4, 0x73, 0x2e, 0xed, 0xba,
	0x6b, 0x3d, 0xb8, 0x33, 0x3c, 0xef, 0x4f, 0x07, 0x7d, 0xdd, 0x23, 0xd0, 0x49, 0x72, 0x05, 0x0d,
	0xcc, 0x50, 0xc4, 0x0b, 0xfb, 0xc4, 0xe8, 0x57, 0x91, 0xce, 0x27, 0x48, 0x53, 0x95, 0xd8, 0xa7,
	0x65, 0xbe, 0x8c, 0x88, 0x03, 0xe7, 0x7c, 0x96, 0xa1, 0x78, 0x7e, 0xf3, 0xc4, 0x6e, 0x98, 0x26,
	0xab, 0x98, 0xdc, 0x87, 0xe6, 0x84, 0x47, 0x98, 0x7e, 0x4b, 0x27, 0x68, 0x9f, 0x99, 0xe2, 0x3a,
	0xe1, 0xdd, 0x40, 0xe7, 0x6b, 0x81, 0x54, 0x61, 0x79, 0xf6, 0x00, 0xdf, 0x14, 0x28, 0x15, 0x69,
	0x41, 0x9d, 0xe6, 0xcc, 0xcc, 0xd0, 0x0c, 0xf4, 0x5f, 0xe2, 0xc2, 0x29, 0x8d, 0x31, 0x53, 0x66,
	0x88, 0x3b, 0x43, 0xd0, 0x07, 0xae, 0x38, 0x65, 0xc1, 0xfb, 0x02, 0xba, 0xdb, 0x52, 0x32, 0xe7,
	0x99, 0xc4, 0x03, 0x5a, 0xe5, 0x05, 0xd5, 0x96, 0x17, 0xe4, 0x7d, 0x0e, 0x9d, 0x27, 0x98, 0xe2,
	0x7f, 0x1f, 0x62, 0x97, 0xf8, 0x18, 0xba, 0xdb, 0xc4, 0xa3, 0x2d, 0x6d, 0x38, 0x8b, 0x0c, 0x72,
	0x49, 0x5f, 0x86, 0x9e, 0x02, 0xe7, 0xe9, 0x1c, 0xc3, 0x62, 0x29, 0xf2, 0x28, 0xd4, 0xab, 0xff,
	0xdf, 0x67, 0xd0, 0x3b, 0xa1, 0x86, 0x62, 0x56, 0x79, 0x37, 0xa8, 0x22, 0x7d, 0xef, 0x11, 0x13,
	0x58, 0x96, 0x4e, 0x4c, 0x69, 0x9d, 0xf0, 0x9e, 0xc3, 0xfb, 0x07, 0xbb, 0x1e, 0x1d, 0xe0, 0x23,
	0xb8, 0x3b, 0xa3, 0xf2, 0xb6, 0x08, 0x43, 0x94, 0xf2, 0xfb, 0x22, 0x35, 0xdd, 0xce, 0x83, 0xed,
	0xa4, 0xf7, 0x31, 0xb4, 0x03, 0x94, 0xa8, 0x5e, 0x70, 0x91, 0x46, 0x47, 0x67, 0xf0, 0xba, 0x40,
	0x36, 0x61, 0x65, 0x53, 0x6f, 0x04, 0xad, 0x6f, 0x50, 0xbd, 0xed, 0x0e, 0x6e, 0xa0, 0xbd, 0xc1,
	0x3a, 0x7a, 0x7e, 0x4f, 0x5b, 0x5a, 0x63, 0x0e, 0x18, 0xa8, 0xaa, 0x0c, 0xff, 0xae, 0x43, 0xfb,
	0x76, 0xf5, 0x50, 0xdf, 0x96, 0xcf, 0x34, 0x79, 0x01, 0x17, 0x9b, 0xbe, 0x22, 0xf7, 0x34, 0xf3,
	0x80, 0x69, 0x1d, 0x7b, 0xbf, 0x50, 0x4d, 0xd6, 0xfd, 0xf9, 0x8f, 0x7f, 0x7e, 0xad, 0x5d, 0x7a,
	0x4d, 0x7f, 0x3a, 0xf0, 0x8d, 0x5b, 0xc7, 0x56, 0x8f, 0xbc, 0x84, 0x8b, 0x4d, 0xf7, 0x94, 0xc2,
	0x07, 0x8c, 0x58, 0x0a, 0x1f, 0x32, 0x9a, 0x77, 0x65, 0x84, 0x5b, 0xe4, 0x72, 0x25, 0xec, 0xff,
	0xc8, 0xa2, 0x9f, 0xc8, 0x1b, 0xe8, 0x1c, 0x58, 0x2f, 0xf9, 0xc0, 0x0c, 0x7d, 0xd4, 0x6d, 0xce,
	0x87, 0x47, 0xeb, 0x55, 0xbf, 0xf7, 0x4c, 0xbf, 0x8e, 0xb3, 0xd3, 0x4f, 0x4f, 0xf3, 0x0c, 0x9a,
	0xab, 0x3d, 0x90, 0xae, 0x16, 0xda, 0x5d, 0xa6, 0xf3, 0xee, 0x4e, 0xb6, 0x12, 0xbd, 0x67, 0x44,
	0xdb, 0xe4, 0x1d, 0x2d, 0x5a, 0xae, 0xa2, 0x9c, 0xe2, 0x19, 0xc0, 0xda, 0x26, 0xc4, 0xb0, 0xf7,
	0xdc, 0xe5, 0x5c, 0xed, 0xa6, 0xb7, 0xef, 0xdc, 0x31, 0x77, 0x2e, 0x74, 0x7d, 0x6c, 0xf5, 0x1e,
	0xff, 0x65, 0xfd, 0xf2, 0xe8, 0x4f, 0x8b, 0x28, 0x20, 0xeb, 0x45, 0xbb, 0xd5, 0xdb, 0xdb, 0x7b,
	0x09, 0x64, 0xfd, 0x4e, 0x77, 0x73, 0xc1, 0x5f, 0x63, 0xa8, 0xc8, 0x27, 0x89, 0x52, 0xb9, 0x1c,
	0xfb, 0x7e, 0xcc, 0x54, 0x52, 0xbc, 0xea, 0x87, 0x7c, 0xe2, 0x2b, 0x14, 0x82, 0x0a, 0x56, 0x4c,
	0x28, 0xf3, 0xd7, 0x14, 0xc7, 0xfe, 0x81, 0x86, 0x09, 0x15, 0x8b, 0x84, 0xa7, 0x29, 0xcd, 0xa2,
	0xaf, 0xe2, 0x09, 0x65, 0xa9, 0x26, 0x0c, 0xeb, 0x83, 0xfe, 0xc3, 0x9e, 0x65, 0x0d, 0x5b, 0x34,
	0xcf, 0x53, 0x16, 0x1a, 0xb8, 0xff, 0x5a, 0xf2, 0x6c, 0xbc, 0x97, 0x09, 0xbe, 0x84, 0xfa, 0xe8,
	0xe1, 0x88, 0x8c, 0xa0, 0x17, 0xa0, 0x2a, 0x44, 0x86, 0x91, 0x3b, 0x4b, 0x30, 0x73, 0x55, 0x82,
	0xae, 0x40, 0xc9, 0x0b, 0x11, 0xa2, 0x1b, 0x71, 0x94, 0x6e, 0xc6, 0x95, 0x8b, 0x73, 0x26, 0x55,
	0x9f, 0x34, 0xe0, 0xe4, 0xb7, 0x9a, 0x75, 0xf6, 0xaa, 0x61, 0x3e, 0x19, 0x9f, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xba, 0xc3, 0x68, 0x4d, 0x9e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulationServiceClient interface {
	// Create new agent
	CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	// Delete an agent
	DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteEntityAction(ctx context.Context, in *ExecuteEntityActionRequest, opts ...grpc.CallOption) (*ExecuteEntityActionResponse, error)
	// Get data for an entity
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// Reset the world
	ResetWorld(ctx context.Context, in *ResetWorldRequest, opts ...grpc.CallOption) (*ResetWorldResponse, error)
}

type simulationServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimulationServiceClient(cc *grpc.ClientConn) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	out := new(CreateEntityResponse)
	err := c.cc.Invoke(ctx, "/v1.SimulationService/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error) {
	out := new(DeleteEntityResponse)
	err := c.cc.Invoke(ctx, "/v1.SimulationService/DeleteEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) ExecuteEntityAction(ctx context.Context, in *ExecuteEntityActionRequest, opts ...grpc.CallOption) (*ExecuteEntityActionResponse, error) {
	out := new(ExecuteEntityActionResponse)
	err := c.cc.Invoke(ctx, "/v1.SimulationService/ExecuteEntityAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, "/v1.SimulationService/GetEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) ResetWorld(ctx context.Context, in *ResetWorldRequest, opts ...grpc.CallOption) (*ResetWorldResponse, error) {
	out := new(ResetWorldResponse)
	err := c.cc.Invoke(ctx, "/v1.SimulationService/ResetWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
type SimulationServiceServer interface {
	// Create new agent
	CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error)
	// Delete an agent
	DeleteEntity(context.Context, *DeleteEntityRequest) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteEntityAction(context.Context, *ExecuteEntityActionRequest) (*ExecuteEntityActionResponse, error)
	// Get data for an entity
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// Reset the world
	ResetWorld(context.Context, *ResetWorldRequest) (*ResetWorldResponse, error)
}

func RegisterSimulationServiceServer(s *grpc.Server, srv SimulationServiceServer) {
	s.RegisterService(&_SimulationService_serviceDesc, srv)
}

func _SimulationService_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SimulationService/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SimulationService/DeleteEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).DeleteEntity(ctx, req.(*DeleteEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_ExecuteEntityAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteEntityActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ExecuteEntityAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SimulationService/ExecuteEntityAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ExecuteEntityAction(ctx, req.(*ExecuteEntityActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SimulationService/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_ResetWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ResetWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SimulationService/ResetWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ResetWorld(ctx, req.(*ResetWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimulationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _SimulationService_CreateEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _SimulationService_DeleteEntity_Handler,
		},
		{
			MethodName: "ExecuteEntityAction",
			Handler:    _SimulationService_ExecuteEntityAction_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _SimulationService_GetEntity_Handler,
		},
		{
			MethodName: "ResetWorld",
			Handler:    _SimulationService_ResetWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulation-service.proto",
}
