// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package endpoints_terrariumai_environment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Taks we have to do
type Entity struct {
	// Unique integer identifier of the agent
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Entity stats
	Class  string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	X      int32  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Energy int32  `protobuf:"varint,5,opt,name=energy,proto3" json:"energy,omitempty"`
	Health int32  `protobuf:"varint,6,opt,name=health,proto3" json:"health,omitempty"`
	// Owner details
	OwnerUID             string   `protobuf:"bytes,7,opt,name=ownerUID,proto3" json:"ownerUID,omitempty"`
	ModelName            string   `protobuf:"bytes,8,opt,name=modelName,proto3" json:"modelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Entity) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Entity) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Entity) GetEnergy() int32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Entity) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Entity) GetOwnerUID() string {
	if m != nil {
		return m.OwnerUID
	}
	return ""
}

func (m *Entity) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

// Request data to create new agent
type CreateEntityRequest struct {
	// agent
	Agent                *Entity  `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityRequest) Reset()         { *m = CreateEntityRequest{} }
func (m *CreateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntityRequest) ProtoMessage()    {}
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{1}
}

func (m *CreateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityRequest.Unmarshal(m, b)
}
func (m *CreateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityRequest.Merge(m, src)
}
func (m *CreateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntityRequest.Size(m)
}
func (m *CreateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityRequest proto.InternalMessageInfo

func (m *CreateEntityRequest) GetAgent() *Entity {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Contains data of created agent
type CreateEntityResponse struct {
	// ID of created agent
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityResponse) Reset()         { *m = CreateEntityResponse{} }
func (m *CreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEntityResponse) ProtoMessage()    {}
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{2}
}

func (m *CreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityResponse.Unmarshal(m, b)
}
func (m *CreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *CreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityResponse.Merge(m, src)
}
func (m *CreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEntityResponse.Size(m)
}
func (m *CreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityResponse proto.InternalMessageInfo

func (m *CreateEntityResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request data to read entity
type GetEntityRequest struct {
	// Unique integer identifier of the agent
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityRequest) Reset()         { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()    {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{3}
}

func (m *GetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityRequest.Unmarshal(m, b)
}
func (m *GetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityRequest.Marshal(b, m, deterministic)
}
func (m *GetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityRequest.Merge(m, src)
}
func (m *GetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntityRequest.Size(m)
}
func (m *GetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityRequest proto.InternalMessageInfo

func (m *GetEntityRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains entity data specified in by ID request
type GetEntityResponse struct {
	// Task entity read by ID
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityResponse) Reset()         { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()    {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{4}
}

func (m *GetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityResponse.Unmarshal(m, b)
}
func (m *GetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityResponse.Marshal(b, m, deterministic)
}
func (m *GetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityResponse.Merge(m, src)
}
func (m *GetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntityResponse.Size(m)
}
func (m *GetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityResponse proto.InternalMessageInfo

func (m *GetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// Request data to delete agent
type DeleteEntityRequest struct {
	// Unique integer identifier of the agent to delete
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityRequest) Reset()         { *m = DeleteEntityRequest{} }
func (m *DeleteEntityRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityRequest) ProtoMessage()    {}
func (*DeleteEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{5}
}

func (m *DeleteEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityRequest.Unmarshal(m, b)
}
func (m *DeleteEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityRequest.Merge(m, src)
}
func (m *DeleteEntityRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityRequest.Size(m)
}
func (m *DeleteEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityRequest proto.InternalMessageInfo

func (m *DeleteEntityRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains status of delete operation
type DeleteEntityResponse struct {
	// Contains number of entities have beed deleted
	// Equals 1 in case of successful delete
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityResponse) Reset()         { *m = DeleteEntityResponse{} }
func (m *DeleteEntityResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityResponse) ProtoMessage()    {}
func (*DeleteEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{6}
}

func (m *DeleteEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityResponse.Unmarshal(m, b)
}
func (m *DeleteEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityResponse.Merge(m, src)
}
func (m *DeleteEntityResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityResponse.Size(m)
}
func (m *DeleteEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityResponse proto.InternalMessageInfo

func (m *DeleteEntityResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ExecuteAgentActionRequest struct {
	// Id for the agent that should perform the action
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// identifier for the action
	// 0: MOVE
	// 1: EAT
	Action uint32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	// direction to perform the action in
	// 0: UP
	// 1: DOWN
	// 2: LEFT
	// 3: RIGHT
	Direction            uint32   `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteAgentActionRequest) Reset()         { *m = ExecuteAgentActionRequest{} }
func (m *ExecuteAgentActionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteAgentActionRequest) ProtoMessage()    {}
func (*ExecuteAgentActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{7}
}

func (m *ExecuteAgentActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteAgentActionRequest.Unmarshal(m, b)
}
func (m *ExecuteAgentActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteAgentActionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteAgentActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteAgentActionRequest.Merge(m, src)
}
func (m *ExecuteAgentActionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteAgentActionRequest.Size(m)
}
func (m *ExecuteAgentActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteAgentActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteAgentActionRequest proto.InternalMessageInfo

func (m *ExecuteAgentActionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExecuteAgentActionRequest) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ExecuteAgentActionRequest) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type ExecuteAgentActionResponse struct {
	// Was the agent able to perform the action
	WasSuccessful        bool     `protobuf:"varint,3,opt,name=wasSuccessful,proto3" json:"wasSuccessful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteAgentActionResponse) Reset()         { *m = ExecuteAgentActionResponse{} }
func (m *ExecuteAgentActionResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteAgentActionResponse) ProtoMessage()    {}
func (*ExecuteAgentActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{8}
}

func (m *ExecuteAgentActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteAgentActionResponse.Unmarshal(m, b)
}
func (m *ExecuteAgentActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteAgentActionResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteAgentActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteAgentActionResponse.Merge(m, src)
}
func (m *ExecuteAgentActionResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteAgentActionResponse.Size(m)
}
func (m *ExecuteAgentActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteAgentActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteAgentActionResponse proto.InternalMessageInfo

func (m *ExecuteAgentActionResponse) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func init() {
	proto.RegisterType((*Entity)(nil), "endpoints.terrariumai.environment.Entity")
	proto.RegisterType((*CreateEntityRequest)(nil), "endpoints.terrariumai.environment.CreateEntityRequest")
	proto.RegisterType((*CreateEntityResponse)(nil), "endpoints.terrariumai.environment.CreateEntityResponse")
	proto.RegisterType((*GetEntityRequest)(nil), "endpoints.terrariumai.environment.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "endpoints.terrariumai.environment.GetEntityResponse")
	proto.RegisterType((*DeleteEntityRequest)(nil), "endpoints.terrariumai.environment.DeleteEntityRequest")
	proto.RegisterType((*DeleteEntityResponse)(nil), "endpoints.terrariumai.environment.DeleteEntityResponse")
	proto.RegisterType((*ExecuteAgentActionRequest)(nil), "endpoints.terrariumai.environment.ExecuteAgentActionRequest")
	proto.RegisterType((*ExecuteAgentActionResponse)(nil), "endpoints.terrariumai.environment.ExecuteAgentActionResponse")
}

func init() { proto.RegisterFile("environment.proto", fileDescriptor_64e647b85623514a) }

var fileDescriptor_64e647b85623514a = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0x93, 0x26, 0x4d, 0x6e, 0x5b, 0x44, 0xa7, 0x51, 0x65, 0x0c, 0x8b, 0x30, 0x02, 0x14,
	0x36, 0x2e, 0x6a, 0x11, 0x6c, 0x78, 0x28, 0xd0, 0x08, 0xb1, 0x61, 0x61, 0x44, 0x59, 0x4f, 0xed,
	0xdb, 0xd4, 0x92, 0x3d, 0x13, 0x66, 0xc6, 0x34, 0x5e, 0xf2, 0x0d, 0xfc, 0x0a, 0xbf, 0xc4, 0x7f,
	0x20, 0xcf, 0x38, 0x2f, 0x93, 0x08, 0x87, 0xe5, 0x39, 0x73, 0xcf, 0x7d, 0x1e, 0x0d, 0x1c, 0x21,
	0xff, 0x1e, 0x4b, 0xc1, 0x53, 0xe4, 0xda, 0x9f, 0x48, 0xa1, 0x05, 0x79, 0x88, 0x3c, 0x9a, 0x88,
	0x98, 0x6b, 0xe5, 0x6b, 0x94, 0x92, 0xc9, 0x38, 0x4b, 0x59, 0xec, 0x2f, 0x05, 0x7a, 0xf7, 0xc7,
	0x42, 0x8c, 0x13, 0x3c, 0x35, 0x82, 0xab, 0xec, 0xfa, 0x14, 0xd3, 0x89, 0xce, 0xad, 0x9e, 0xfe,
	0x72, 0xa0, 0x3d, 0xe2, 0x3a, 0xd6, 0x39, 0xb9, 0x03, 0x8d, 0x38, 0x72, 0x9d, 0xbe, 0x33, 0x68,
	0x06, 0x8d, 0x38, 0x22, 0x3d, 0x68, 0x85, 0x09, 0x53, 0xca, 0x6d, 0xf4, 0x9d, 0x41, 0x37, 0xb0,
	0x80, 0x1c, 0x80, 0x33, 0x75, 0x9b, 0x7d, 0x67, 0xd0, 0x0a, 0x9c, 0x69, 0x81, 0x72, 0x77, 0xd7,
	0xa2, 0x9c, 0x9c, 0x40, 0x1b, 0x39, 0xca, 0x71, 0xee, 0xb6, 0x0c, 0x55, 0xa2, 0x82, 0xbf, 0x41,
	0x96, 0xe8, 0x1b, 0xb7, 0x6d, 0x79, 0x8b, 0x88, 0x07, 0x1d, 0x71, 0xcb, 0x51, 0x7e, 0xf9, 0x78,
	0xe1, 0xee, 0x99, 0x22, 0x73, 0x4c, 0x1e, 0x40, 0x37, 0x15, 0x11, 0x26, 0x9f, 0x58, 0x8a, 0x6e,
	0xc7, 0x3c, 0x2e, 0x08, 0x7a, 0x09, 0xc7, 0xef, 0x25, 0x32, 0x8d, 0xb6, 0xf7, 0x00, 0xbf, 0x65,
	0xa8, 0x34, 0x79, 0x0b, 0x2d, 0x36, 0x46, 0xae, 0xcd, 0x14, 0xfb, 0x67, 0x4f, 0xfd, 0x7f, 0x6e,
	0xc7, 0x2f, 0x13, 0x58, 0x1d, 0x7d, 0x02, 0xbd, 0xd5, 0xbc, 0x6a, 0x22, 0xb8, 0xc2, 0xea, 0x6e,
	0x28, 0x85, 0xbb, 0x1f, 0x50, 0xaf, 0x16, 0xaf, 0xc6, 0x5c, 0xc2, 0xd1, 0x52, 0x4c, 0x99, 0x68,
	0x58, 0xac, 0xa8, 0x60, 0xb6, 0x6f, 0xb1, 0x14, 0xd2, 0xc7, 0x70, 0x7c, 0x81, 0x09, 0x56, 0x67,
	0xaf, 0x96, 0x7f, 0x06, 0xbd, 0xd5, 0xb0, 0xb2, 0x03, 0x17, 0xf6, 0x22, 0xc3, 0xcf, 0x82, 0x67,
	0x90, 0x32, 0xb8, 0x37, 0x9a, 0x62, 0x98, 0x69, 0x1c, 0x16, 0xcb, 0x18, 0x86, 0x3a, 0x16, 0x7c,
	0x43, 0xfa, 0xe2, 0xa6, 0xcc, 0x04, 0x18, 0x7b, 0x1c, 0x06, 0x25, 0x2a, 0xee, 0x16, 0xc5, 0x12,
	0xed, 0x53, 0xd3, 0x3c, 0x2d, 0x08, 0xfa, 0x0e, 0xbc, 0x75, 0x25, 0xca, 0xd6, 0x1e, 0xc1, 0xe1,
	0x2d, 0x53, 0x9f, 0xb3, 0x30, 0x44, 0xa5, 0xae, 0xb3, 0xc4, 0xe8, 0x3b, 0xc1, 0x2a, 0x79, 0xf6,
	0x7b, 0x17, 0xf6, 0x47, 0x8b, 0xf5, 0x90, 0x1f, 0x0e, 0x1c, 0x2c, 0x1f, 0x8d, 0xbc, 0xa8, 0xb1,
	0xd3, 0x35, 0xee, 0xf1, 0x5e, 0x6e, 0xad, 0xb3, 0x7d, 0xd3, 0x1d, 0x32, 0x85, 0xee, 0xfc, 0xd6,
	0xe4, 0xbc, 0x46, 0x9e, 0xaa, 0x7b, 0xbc, 0xe7, 0xdb, 0x89, 0xe6, 0x95, 0x8b, 0xe9, 0x97, 0xef,
	0x5c, 0x6b, 0xfa, 0x35, 0xfe, 0xa9, 0x35, 0xfd, 0x3a, 0x43, 0xd1, 0x1d, 0xf2, 0xd3, 0x01, 0xf2,
	0xf7, 0x59, 0xc9, 0xab, 0x3a, 0xde, 0xde, 0x64, 0x38, 0xef, 0xf5, 0x7f, 0xaa, 0xe7, 0x5d, 0xbd,
	0x01, 0x08, 0x50, 0xa1, 0xfe, 0x2a, 0x64, 0x12, 0x91, 0x13, 0xdf, 0x7e, 0x83, 0xfe, 0xec, 0x1b,
	0xf4, 0x47, 0xc5, 0x37, 0xe8, 0x6d, 0xe0, 0xe9, 0xce, 0x55, 0xdb, 0x30, 0xe7, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0x95, 0x7d, 0x48, 0x76, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnvironmentClient is the client API for Environment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnvironmentClient interface {
	// Create new agent
	CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	// Get data for an entity
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// Delete an agent
	DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteAgentAction(ctx context.Context, in *ExecuteAgentActionRequest, opts ...grpc.CallOption) (*ExecuteAgentActionResponse, error)
	// Reset the world
	ResetWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type environmentClient struct {
	cc *grpc.ClientConn
}

func NewEnvironmentClient(cc *grpc.ClientConn) EnvironmentClient {
	return &environmentClient{cc}
}

func (c *environmentClient) CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	out := new(CreateEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/GetEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error) {
	out := new(DeleteEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/DeleteEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) ExecuteAgentAction(ctx context.Context, in *ExecuteAgentActionRequest, opts ...grpc.CallOption) (*ExecuteAgentActionResponse, error) {
	out := new(ExecuteAgentActionResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/ExecuteAgentAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) ResetWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/ResetWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvironmentServer is the server API for Environment service.
type EnvironmentServer interface {
	// Create new agent
	CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error)
	// Get data for an entity
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// Delete an agent
	DeleteEntity(context.Context, *DeleteEntityRequest) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteAgentAction(context.Context, *ExecuteAgentActionRequest) (*ExecuteAgentActionResponse, error)
	// Reset the world
	ResetWorld(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterEnvironmentServer(s *grpc.Server, srv EnvironmentServer) {
	s.RegisterService(&_Environment_serviceDesc, srv)
}

func _Environment_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/DeleteEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).DeleteEntity(ctx, req.(*DeleteEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_ExecuteAgentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAgentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).ExecuteAgentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/ExecuteAgentAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).ExecuteAgentAction(ctx, req.(*ExecuteAgentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_ResetWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).ResetWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/ResetWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).ResetWorld(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Environment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "endpoints.terrariumai.environment.Environment",
	HandlerType: (*EnvironmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _Environment_CreateEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _Environment_GetEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _Environment_DeleteEntity_Handler,
		},
		{
			MethodName: "ExecuteAgentAction",
			Handler:    _Environment_ExecuteAgentAction_Handler,
		},
		{
			MethodName: "ResetWorld",
			Handler:    _Environment_ResetWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environment.proto",
}
