// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package endpoints_terrariumai_environment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Class
type Effect_Class int32

const (
	Effect_PHEROMONE Effect_Class = 0
)

var Effect_Class_name = map[int32]string{
	0: "PHEROMONE",
}

var Effect_Class_value = map[string]int32{
	"PHEROMONE": 0,
}

func (x Effect_Class) String() string {
	return proto.EnumName(Effect_Class_name, int32(x))
}

func (Effect_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{1, 0}
}

// Taks we have to do
type Entity struct {
	// Unique integer identifier of the agent
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Entity stats
	// 0: Empty
	// 1: Agent
	// 2: Rock
	// 3: Food
	ClassID uint32 `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`
	X       uint32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y       uint32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Energy  uint32 `protobuf:"varint,5,opt,name=energy,proto3" json:"energy,omitempty"`
	Health  uint32 `protobuf:"varint,6,opt,name=health,proto3" json:"health,omitempty"`
	// Owner details
	OwnerUID             string   `protobuf:"bytes,7,opt,name=ownerUID,proto3" json:"ownerUID,omitempty"`
	ModelID              string   `protobuf:"bytes,8,opt,name=modelID,proto3" json:"modelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetClassID() uint32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

func (m *Entity) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Entity) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Entity) GetEnergy() uint32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Entity) GetHealth() uint32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Entity) GetOwnerUID() string {
	if m != nil {
		return m.OwnerUID
	}
	return ""
}

func (m *Entity) GetModelID() string {
	if m != nil {
		return m.ModelID
	}
	return ""
}

// Effects are manipulations of a cell that last a specific amount of time
type Effect struct {
	// Pos
	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	// Time of creation
	Timestamp int64        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClassID   Effect_Class `protobuf:"varint,4,opt,name=classID,proto3,enum=endpoints.terrariumai.environment.Effect_Class" json:"classID,omitempty"`
	// Value, used for observation
	Value uint32 `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	// How fast it should decay
	Decay float32 `protobuf:"fixed32,6,opt,name=decay,proto3" json:"decay,omitempty"`
	// Min before being deleted
	DelThresh            uint32   `protobuf:"varint,7,opt,name=delThresh,proto3" json:"delThresh,omitempty"`
	Strength             uint32   `protobuf:"varint,8,opt,name=strength,proto3" json:"strength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Effect) Reset()         { *m = Effect{} }
func (m *Effect) String() string { return proto.CompactTextString(m) }
func (*Effect) ProtoMessage()    {}
func (*Effect) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{1}
}

func (m *Effect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Effect.Unmarshal(m, b)
}
func (m *Effect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Effect.Marshal(b, m, deterministic)
}
func (m *Effect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Effect.Merge(m, src)
}
func (m *Effect) XXX_Size() int {
	return xxx_messageInfo_Effect.Size(m)
}
func (m *Effect) XXX_DiscardUnknown() {
	xxx_messageInfo_Effect.DiscardUnknown(m)
}

var xxx_messageInfo_Effect proto.InternalMessageInfo

func (m *Effect) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Effect) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Effect) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Effect) GetClassID() Effect_Class {
	if m != nil {
		return m.ClassID
	}
	return Effect_PHEROMONE
}

func (m *Effect) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Effect) GetDecay() float32 {
	if m != nil {
		return m.Decay
	}
	return 0
}

func (m *Effect) GetDelThresh() uint32 {
	if m != nil {
		return m.DelThresh
	}
	return 0
}

func (m *Effect) GetStrength() uint32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

// Request data to create new agent
type CreateEntityRequest struct {
	// agent
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityRequest) Reset()         { *m = CreateEntityRequest{} }
func (m *CreateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntityRequest) ProtoMessage()    {}
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{2}
}

func (m *CreateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityRequest.Unmarshal(m, b)
}
func (m *CreateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityRequest.Merge(m, src)
}
func (m *CreateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntityRequest.Size(m)
}
func (m *CreateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityRequest proto.InternalMessageInfo

func (m *CreateEntityRequest) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// Contains data of created agent
type CreateEntityResponse struct {
	// ID of created agent
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityResponse) Reset()         { *m = CreateEntityResponse{} }
func (m *CreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEntityResponse) ProtoMessage()    {}
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{3}
}

func (m *CreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityResponse.Unmarshal(m, b)
}
func (m *CreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *CreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityResponse.Merge(m, src)
}
func (m *CreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEntityResponse.Size(m)
}
func (m *CreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityResponse proto.InternalMessageInfo

func (m *CreateEntityResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Request data to read entity
type GetEntityRequest struct {
	// Unique integer identifier of the agent
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityRequest) Reset()         { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()    {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{4}
}

func (m *GetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityRequest.Unmarshal(m, b)
}
func (m *GetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityRequest.Marshal(b, m, deterministic)
}
func (m *GetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityRequest.Merge(m, src)
}
func (m *GetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntityRequest.Size(m)
}
func (m *GetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityRequest proto.InternalMessageInfo

func (m *GetEntityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Contains entity data specified in by ID request
type GetEntityResponse struct {
	// Task entity read by ID
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityResponse) Reset()         { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()    {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{5}
}

func (m *GetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityResponse.Unmarshal(m, b)
}
func (m *GetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityResponse.Marshal(b, m, deterministic)
}
func (m *GetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityResponse.Merge(m, src)
}
func (m *GetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntityResponse.Size(m)
}
func (m *GetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityResponse proto.InternalMessageInfo

func (m *GetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// Request data to delete agent
type DeleteEntityRequest struct {
	// Unique integer identifier of the agent to delete
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityRequest) Reset()         { *m = DeleteEntityRequest{} }
func (m *DeleteEntityRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityRequest) ProtoMessage()    {}
func (*DeleteEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{6}
}

func (m *DeleteEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityRequest.Unmarshal(m, b)
}
func (m *DeleteEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityRequest.Merge(m, src)
}
func (m *DeleteEntityRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityRequest.Size(m)
}
func (m *DeleteEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityRequest proto.InternalMessageInfo

func (m *DeleteEntityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Contains status of delete operation
type DeleteEntityResponse struct {
	// Contains number of entities have beed deleted
	// Equals 1 in case of successful delete
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityResponse) Reset()         { *m = DeleteEntityResponse{} }
func (m *DeleteEntityResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityResponse) ProtoMessage()    {}
func (*DeleteEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{7}
}

func (m *DeleteEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityResponse.Unmarshal(m, b)
}
func (m *DeleteEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityResponse.Merge(m, src)
}
func (m *DeleteEntityResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityResponse.Size(m)
}
func (m *DeleteEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityResponse proto.InternalMessageInfo

func (m *DeleteEntityResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ExecuteAgentActionRequest struct {
	// Id for the agent that should perform the action
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// identifier for the action
	// 0: WAIT
	// 1: MOVE
	// 2: EAT
	// 3: ATTACK
	Action uint32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	// direction to perform the action in
	// 0: UP
	// 1: DOWN
	// 2: LEFT
	// 3: RIGHT
	Direction            uint32   `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteAgentActionRequest) Reset()         { *m = ExecuteAgentActionRequest{} }
func (m *ExecuteAgentActionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteAgentActionRequest) ProtoMessage()    {}
func (*ExecuteAgentActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{8}
}

func (m *ExecuteAgentActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteAgentActionRequest.Unmarshal(m, b)
}
func (m *ExecuteAgentActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteAgentActionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteAgentActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteAgentActionRequest.Merge(m, src)
}
func (m *ExecuteAgentActionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteAgentActionRequest.Size(m)
}
func (m *ExecuteAgentActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteAgentActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteAgentActionRequest proto.InternalMessageInfo

func (m *ExecuteAgentActionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExecuteAgentActionRequest) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ExecuteAgentActionRequest) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type ExecuteAgentActionResponse struct {
	// Was the agent able to perform the action
	WasSuccessful bool `protobuf:"varint,1,opt,name=wasSuccessful,proto3" json:"wasSuccessful,omitempty"`
	// Is the agent still alive
	IsAlive              bool     `protobuf:"varint,2,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteAgentActionResponse) Reset()         { *m = ExecuteAgentActionResponse{} }
func (m *ExecuteAgentActionResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteAgentActionResponse) ProtoMessage()    {}
func (*ExecuteAgentActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{9}
}

func (m *ExecuteAgentActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteAgentActionResponse.Unmarshal(m, b)
}
func (m *ExecuteAgentActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteAgentActionResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteAgentActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteAgentActionResponse.Merge(m, src)
}
func (m *ExecuteAgentActionResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteAgentActionResponse.Size(m)
}
func (m *ExecuteAgentActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteAgentActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteAgentActionResponse proto.InternalMessageInfo

func (m *ExecuteAgentActionResponse) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func (m *ExecuteAgentActionResponse) GetIsAlive() bool {
	if m != nil {
		return m.IsAlive
	}
	return false
}

type GetEntitiesInRegionRequest struct {
	X                    uint32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitiesInRegionRequest) Reset()         { *m = GetEntitiesInRegionRequest{} }
func (m *GetEntitiesInRegionRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntitiesInRegionRequest) ProtoMessage()    {}
func (*GetEntitiesInRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{10}
}

func (m *GetEntitiesInRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitiesInRegionRequest.Unmarshal(m, b)
}
func (m *GetEntitiesInRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitiesInRegionRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitiesInRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitiesInRegionRequest.Merge(m, src)
}
func (m *GetEntitiesInRegionRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitiesInRegionRequest.Size(m)
}
func (m *GetEntitiesInRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitiesInRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitiesInRegionRequest proto.InternalMessageInfo

func (m *GetEntitiesInRegionRequest) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetEntitiesInRegionRequest) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GetEntitiesInRegionResponse struct {
	Entities             []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetEntitiesInRegionResponse) Reset()         { *m = GetEntitiesInRegionResponse{} }
func (m *GetEntitiesInRegionResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntitiesInRegionResponse) ProtoMessage()    {}
func (*GetEntitiesInRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{11}
}

func (m *GetEntitiesInRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitiesInRegionResponse.Unmarshal(m, b)
}
func (m *GetEntitiesInRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitiesInRegionResponse.Marshal(b, m, deterministic)
}
func (m *GetEntitiesInRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitiesInRegionResponse.Merge(m, src)
}
func (m *GetEntitiesInRegionResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntitiesInRegionResponse.Size(m)
}
func (m *GetEntitiesInRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitiesInRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitiesInRegionResponse proto.InternalMessageInfo

func (m *GetEntitiesInRegionResponse) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type GetEffectsInRegionRequest struct {
	X                    uint32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEffectsInRegionRequest) Reset()         { *m = GetEffectsInRegionRequest{} }
func (m *GetEffectsInRegionRequest) String() string { return proto.CompactTextString(m) }
func (*GetEffectsInRegionRequest) ProtoMessage()    {}
func (*GetEffectsInRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{12}
}

func (m *GetEffectsInRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEffectsInRegionRequest.Unmarshal(m, b)
}
func (m *GetEffectsInRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEffectsInRegionRequest.Marshal(b, m, deterministic)
}
func (m *GetEffectsInRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEffectsInRegionRequest.Merge(m, src)
}
func (m *GetEffectsInRegionRequest) XXX_Size() int {
	return xxx_messageInfo_GetEffectsInRegionRequest.Size(m)
}
func (m *GetEffectsInRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEffectsInRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEffectsInRegionRequest proto.InternalMessageInfo

func (m *GetEffectsInRegionRequest) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetEffectsInRegionRequest) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GetEffectsInRegionResponse struct {
	Effects              []*Effect `protobuf:"bytes,1,rep,name=effects,proto3" json:"effects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetEffectsInRegionResponse) Reset()         { *m = GetEffectsInRegionResponse{} }
func (m *GetEffectsInRegionResponse) String() string { return proto.CompactTextString(m) }
func (*GetEffectsInRegionResponse) ProtoMessage()    {}
func (*GetEffectsInRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{13}
}

func (m *GetEffectsInRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEffectsInRegionResponse.Unmarshal(m, b)
}
func (m *GetEffectsInRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEffectsInRegionResponse.Marshal(b, m, deterministic)
}
func (m *GetEffectsInRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEffectsInRegionResponse.Merge(m, src)
}
func (m *GetEffectsInRegionResponse) XXX_Size() int {
	return xxx_messageInfo_GetEffectsInRegionResponse.Size(m)
}
func (m *GetEffectsInRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEffectsInRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEffectsInRegionResponse proto.InternalMessageInfo

func (m *GetEffectsInRegionResponse) GetEffects() []*Effect {
	if m != nil {
		return m.Effects
	}
	return nil
}

func init() {
	proto.RegisterEnum("endpoints.terrariumai.environment.Effect_Class", Effect_Class_name, Effect_Class_value)
	proto.RegisterType((*Entity)(nil), "endpoints.terrariumai.environment.Entity")
	proto.RegisterType((*Effect)(nil), "endpoints.terrariumai.environment.Effect")
	proto.RegisterType((*CreateEntityRequest)(nil), "endpoints.terrariumai.environment.CreateEntityRequest")
	proto.RegisterType((*CreateEntityResponse)(nil), "endpoints.terrariumai.environment.CreateEntityResponse")
	proto.RegisterType((*GetEntityRequest)(nil), "endpoints.terrariumai.environment.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "endpoints.terrariumai.environment.GetEntityResponse")
	proto.RegisterType((*DeleteEntityRequest)(nil), "endpoints.terrariumai.environment.DeleteEntityRequest")
	proto.RegisterType((*DeleteEntityResponse)(nil), "endpoints.terrariumai.environment.DeleteEntityResponse")
	proto.RegisterType((*ExecuteAgentActionRequest)(nil), "endpoints.terrariumai.environment.ExecuteAgentActionRequest")
	proto.RegisterType((*ExecuteAgentActionResponse)(nil), "endpoints.terrariumai.environment.ExecuteAgentActionResponse")
	proto.RegisterType((*GetEntitiesInRegionRequest)(nil), "endpoints.terrariumai.environment.GetEntitiesInRegionRequest")
	proto.RegisterType((*GetEntitiesInRegionResponse)(nil), "endpoints.terrariumai.environment.GetEntitiesInRegionResponse")
	proto.RegisterType((*GetEffectsInRegionRequest)(nil), "endpoints.terrariumai.environment.GetEffectsInRegionRequest")
	proto.RegisterType((*GetEffectsInRegionResponse)(nil), "endpoints.terrariumai.environment.GetEffectsInRegionResponse")
}

func init() { proto.RegisterFile("environment.proto", fileDescriptor_64e647b85623514a) }

var fileDescriptor_64e647b85623514a = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x93, 0xaf, 0xf9, 0xb9, 0x6d, 0xaa, 0x76, 0x5a, 0x55, 0xae, 0xfb, 0x2d, 0xca, 0x08,
	0x50, 0xd9, 0xb8, 0xa8, 0x45, 0x94, 0x05, 0xa9, 0x14, 0x35, 0x06, 0xb2, 0x80, 0x22, 0x97, 0xbf,
	0x05, 0x1b, 0x37, 0xbe, 0x49, 0x2c, 0x39, 0xe3, 0xe0, 0x99, 0xb4, 0xc9, 0x92, 0x35, 0x4b, 0x24,
	0x9e, 0x84, 0x37, 0xe1, 0x85, 0xd0, 0xcc, 0xd8, 0xf9, 0x6b, 0x02, 0x49, 0xc4, 0xf2, 0xdc, 0x99,
	0x33, 0xf7, 0x9c, 0xb9, 0x3e, 0x1e, 0xd8, 0x46, 0x76, 0x13, 0xc4, 0x11, 0xeb, 0x20, 0x13, 0x76,
	0x37, 0x8e, 0x44, 0x44, 0xee, 0x21, 0xf3, 0xbb, 0x51, 0xc0, 0x04, 0xb7, 0x05, 0xc6, 0xb1, 0x17,
	0x07, 0xbd, 0x8e, 0x17, 0xd8, 0x63, 0x1b, 0xad, 0x83, 0x56, 0x14, 0xb5, 0x42, 0x3c, 0x56, 0x84,
	0xeb, 0x5e, 0xf3, 0x18, 0x3b, 0x5d, 0x31, 0xd0, 0x7c, 0xfa, 0xd3, 0x80, 0xbc, 0xc3, 0x44, 0x20,
	0x06, 0x64, 0x13, 0xb2, 0x81, 0x6f, 0x1a, 0x87, 0xc6, 0x51, 0xc9, 0xcd, 0x06, 0x3e, 0x31, 0xa1,
	0xd0, 0x08, 0x3d, 0xce, 0xeb, 0x35, 0x33, 0x7b, 0x68, 0x1c, 0x95, 0xdd, 0x14, 0x92, 0x0d, 0x30,
	0xfa, 0x66, 0x4e, 0xd5, 0x8c, 0xbe, 0x44, 0x03, 0xf3, 0x3f, 0x8d, 0x06, 0x64, 0x0f, 0xf2, 0xc8,
	0x30, 0x6e, 0x0d, 0xcc, 0x35, 0x55, 0x4a, 0x90, 0xac, 0xb7, 0xd1, 0x0b, 0x45, 0xdb, 0xcc, 0xeb,
	0xba, 0x46, 0xc4, 0x82, 0x62, 0x74, 0xcb, 0x30, 0x7e, 0x5f, 0xaf, 0x99, 0x05, 0xd5, 0x7b, 0x88,
	0xa5, 0x82, 0x4e, 0xe4, 0x63, 0x58, 0xaf, 0x99, 0x45, 0xb5, 0x94, 0x42, 0xfa, 0x2d, 0x0b, 0x79,
	0xa7, 0xd9, 0xc4, 0x86, 0xd0, 0x62, 0x8c, 0x09, 0x31, 0xd9, 0x54, 0xcc, 0xff, 0x50, 0x12, 0x41,
	0x07, 0xb9, 0xf0, 0x3a, 0x5d, 0x25, 0x38, 0xe7, 0x8e, 0x0a, 0xa4, 0x3e, 0x32, 0x28, 0xe5, 0x6f,
	0x9e, 0x1c, 0xdb, 0x7f, 0xbd, 0x4d, 0x5b, 0x77, 0xb5, 0x2f, 0x24, 0x71, 0x74, 0x23, 0xbb, 0xb0,
	0x76, 0xe3, 0x85, 0x3d, 0x4c, 0x4c, 0x6b, 0x20, 0xab, 0x3e, 0x36, 0xbc, 0x81, 0xb2, 0x9c, 0x75,
	0x35, 0x90, 0xa2, 0x7c, 0x0c, 0xdf, 0xb5, 0x63, 0xe4, 0x6d, 0x65, 0xb9, 0xec, 0x8e, 0x0a, 0xf2,
	0x3e, 0xb8, 0x88, 0x91, 0xb5, 0x44, 0x5b, 0x99, 0x2e, 0xbb, 0x43, 0x4c, 0xf7, 0x60, 0x4d, 0xf5,
	0x25, 0x65, 0x28, 0xbd, 0x7d, 0xe5, 0xb8, 0x97, 0xaf, 0x2f, 0xdf, 0x38, 0x5b, 0x19, 0xfa, 0x09,
	0x76, 0x2e, 0x62, 0xf4, 0x04, 0xea, 0x49, 0xba, 0xf8, 0xa5, 0x87, 0x5c, 0x90, 0xaa, 0x1c, 0x85,
	0x2c, 0xa8, 0xeb, 0x59, 0x3f, 0x79, 0xb4, 0x88, 0x3d, 0x7d, 0x42, 0x42, 0xa4, 0x0f, 0x61, 0x77,
	0xf2, 0x64, 0xde, 0x8d, 0x18, 0xc7, 0xe9, 0x6f, 0x85, 0x52, 0xd8, 0x7a, 0x89, 0x62, 0xb2, 0xfd,
	0xf4, 0x9e, 0x0f, 0xb0, 0x3d, 0xb6, 0x27, 0x39, 0xe8, 0x1f, 0x68, 0x7c, 0x00, 0x3b, 0x35, 0x0c,
	0x71, 0xda, 0xfd, 0x74, 0xfb, 0xc7, 0xb0, 0x3b, 0xb9, 0x2d, 0x51, 0x60, 0x42, 0xc1, 0x57, 0x75,
	0xbd, 0x39, 0xe7, 0xa6, 0x90, 0x7a, 0xb0, 0xef, 0xf4, 0xb1, 0xd1, 0x13, 0x58, 0x6d, 0x21, 0x13,
	0xd5, 0x86, 0x08, 0x22, 0x36, 0xe7, 0x78, 0xf9, 0x7d, 0x7b, 0x6a, 0x43, 0xf2, 0xf5, 0x25, 0x48,
	0x4d, 0x3b, 0x88, 0x51, 0x2f, 0xe5, 0x92, 0x69, 0xa7, 0x05, 0xfa, 0x19, 0xac, 0x59, 0x2d, 0x12,
	0x69, 0xf7, 0xa1, 0x7c, 0xeb, 0xf1, 0xab, 0x5e, 0xa3, 0x81, 0x9c, 0x37, 0x7b, 0xa1, 0x6a, 0x57,
	0x74, 0x27, 0x8b, 0xd2, 0x40, 0xc0, 0xab, 0x61, 0x70, 0x83, 0xaa, 0x75, 0xd1, 0x4d, 0x21, 0x7d,
	0x06, 0x56, 0x7a, 0xe3, 0x01, 0xf2, 0x3a, 0x73, 0xb1, 0x35, 0xe6, 0xe0, 0x0f, 0xc1, 0xa1, 0x3e,
	0x1c, 0xcc, 0x64, 0x26, 0xc2, 0x1c, 0x28, 0x62, 0xb2, 0x66, 0x1a, 0x87, 0xb9, 0xe5, 0xe6, 0x36,
	0xa4, 0xd2, 0x33, 0xd8, 0x97, 0x5d, 0x54, 0xa2, 0x96, 0x92, 0xe7, 0x69, 0x63, 0xd3, 0xc4, 0x44,
	0xdd, 0x05, 0x14, 0x50, 0x2f, 0x2d, 0x23, 0x4e, 0x31, 0xdc, 0x94, 0x79, 0xf2, 0xab, 0x00, 0xeb,
	0xce, 0x68, 0x9d, 0x7c, 0x35, 0x60, 0x63, 0x3c, 0x0a, 0xe4, 0xe9, 0x02, 0x87, 0xce, 0x48, 0xa5,
	0x75, 0xb6, 0x34, 0x4f, 0xdb, 0xa2, 0x19, 0xd2, 0x87, 0xd2, 0x30, 0x41, 0xe4, 0x74, 0x81, 0x73,
	0xa6, 0x33, 0x69, 0x3d, 0x59, 0x8e, 0x34, 0xec, 0x2c, 0xdd, 0x8f, 0xa7, 0x67, 0x21, 0xf7, 0x33,
	0x52, 0xb9, 0x90, 0xfb, 0x59, 0x31, 0xa5, 0x19, 0xf2, 0xdd, 0x00, 0x72, 0x37, 0x2c, 0xe4, 0xf9,
	0x22, 0xc3, 0x9d, 0x17, 0x63, 0xab, 0xb2, 0x22, 0x7b, 0xa8, 0xea, 0x1c, 0xc0, 0x45, 0x8e, 0xe2,
	0x63, 0x14, 0x87, 0x3e, 0xd9, 0xb3, 0xf5, 0x63, 0x6b, 0xa7, 0x8f, 0xad, 0xed, 0xc8, 0xc7, 0xd6,
	0x9a, 0x53, 0xa7, 0x19, 0x52, 0x81, 0xd2, 0x55, 0xd7, 0xbb, 0x65, 0x2f, 0xa2, 0x68, 0x15, 0xfa,
	0x0f, 0x03, 0x76, 0x66, 0x24, 0x95, 0x54, 0x96, 0x18, 0xf4, 0xdd, 0x7f, 0x83, 0x75, 0xbe, 0x2a,
	0x7d, 0x62, 0x5a, 0x77, 0x33, 0xba, 0xd0, 0xb4, 0xe6, 0xfe, 0x13, 0xac, 0xca, 0x8a, 0xec, 0x54,
	0xd5, 0x75, 0x5e, 0x5d, 0xe0, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x0c, 0x90, 0x9e,
	0x4a, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnvironmentClient is the client API for Environment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnvironmentClient interface {
	// Create new agent
	CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	// Get data for an entity
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// Delete an agent
	DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteAgentAction(ctx context.Context, in *ExecuteAgentActionRequest, opts ...grpc.CallOption) (*ExecuteAgentActionResponse, error)
	// Reset the world
	ResetWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Spawn food in the world
	SpawnFood(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get Region
	GetEntitiesInRegion(ctx context.Context, in *GetEntitiesInRegionRequest, opts ...grpc.CallOption) (*GetEntitiesInRegionResponse, error)
	GetEffectsInRegion(ctx context.Context, in *GetEffectsInRegionRequest, opts ...grpc.CallOption) (*GetEffectsInRegionResponse, error)
}

type environmentClient struct {
	cc *grpc.ClientConn
}

func NewEnvironmentClient(cc *grpc.ClientConn) EnvironmentClient {
	return &environmentClient{cc}
}

func (c *environmentClient) CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	out := new(CreateEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/GetEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) DeleteEntity(ctx context.Context, in *DeleteEntityRequest, opts ...grpc.CallOption) (*DeleteEntityResponse, error) {
	out := new(DeleteEntityResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/DeleteEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) ExecuteAgentAction(ctx context.Context, in *ExecuteAgentActionRequest, opts ...grpc.CallOption) (*ExecuteAgentActionResponse, error) {
	out := new(ExecuteAgentActionResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/ExecuteAgentAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) ResetWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/ResetWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) SpawnFood(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/SpawnFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) GetEntitiesInRegion(ctx context.Context, in *GetEntitiesInRegionRequest, opts ...grpc.CallOption) (*GetEntitiesInRegionResponse, error) {
	out := new(GetEntitiesInRegionResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/GetEntitiesInRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) GetEffectsInRegion(ctx context.Context, in *GetEffectsInRegionRequest, opts ...grpc.CallOption) (*GetEffectsInRegionResponse, error) {
	out := new(GetEffectsInRegionResponse)
	err := c.cc.Invoke(ctx, "/endpoints.terrariumai.environment.Environment/GetEffectsInRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvironmentServer is the server API for Environment service.
type EnvironmentServer interface {
	// Create new agent
	CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error)
	// Get data for an entity
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// Delete an agent
	DeleteEntity(context.Context, *DeleteEntityRequest) (*DeleteEntityResponse, error)
	// Perform an action for an agent
	ExecuteAgentAction(context.Context, *ExecuteAgentActionRequest) (*ExecuteAgentActionResponse, error)
	// Reset the world
	ResetWorld(context.Context, *empty.Empty) (*empty.Empty, error)
	// Spawn food in the world
	SpawnFood(context.Context, *empty.Empty) (*empty.Empty, error)
	// Get Region
	GetEntitiesInRegion(context.Context, *GetEntitiesInRegionRequest) (*GetEntitiesInRegionResponse, error)
	GetEffectsInRegion(context.Context, *GetEffectsInRegionRequest) (*GetEffectsInRegionResponse, error)
}

// UnimplementedEnvironmentServer can be embedded to have forward compatible implementations.
type UnimplementedEnvironmentServer struct {
}

func (*UnimplementedEnvironmentServer) CreateEntity(ctx context.Context, req *CreateEntityRequest) (*CreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedEnvironmentServer) GetEntity(ctx context.Context, req *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (*UnimplementedEnvironmentServer) DeleteEntity(ctx context.Context, req *DeleteEntityRequest) (*DeleteEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntity not implemented")
}
func (*UnimplementedEnvironmentServer) ExecuteAgentAction(ctx context.Context, req *ExecuteAgentActionRequest) (*ExecuteAgentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAgentAction not implemented")
}
func (*UnimplementedEnvironmentServer) ResetWorld(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetWorld not implemented")
}
func (*UnimplementedEnvironmentServer) SpawnFood(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnFood not implemented")
}
func (*UnimplementedEnvironmentServer) GetEntitiesInRegion(ctx context.Context, req *GetEntitiesInRegionRequest) (*GetEntitiesInRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitiesInRegion not implemented")
}
func (*UnimplementedEnvironmentServer) GetEffectsInRegion(ctx context.Context, req *GetEffectsInRegionRequest) (*GetEffectsInRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEffectsInRegion not implemented")
}

func RegisterEnvironmentServer(s *grpc.Server, srv EnvironmentServer) {
	s.RegisterService(&_Environment_serviceDesc, srv)
}

func _Environment_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/DeleteEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).DeleteEntity(ctx, req.(*DeleteEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_ExecuteAgentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAgentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).ExecuteAgentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/ExecuteAgentAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).ExecuteAgentAction(ctx, req.(*ExecuteAgentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_ResetWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).ResetWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/ResetWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).ResetWorld(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_SpawnFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).SpawnFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/SpawnFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).SpawnFood(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_GetEntitiesInRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitiesInRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).GetEntitiesInRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/GetEntitiesInRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).GetEntitiesInRegion(ctx, req.(*GetEntitiesInRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_GetEffectsInRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectsInRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).GetEffectsInRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/endpoints.terrariumai.environment.Environment/GetEffectsInRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).GetEffectsInRegion(ctx, req.(*GetEffectsInRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Environment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "endpoints.terrariumai.environment.Environment",
	HandlerType: (*EnvironmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _Environment_CreateEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _Environment_GetEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _Environment_DeleteEntity_Handler,
		},
		{
			MethodName: "ExecuteAgentAction",
			Handler:    _Environment_ExecuteAgentAction_Handler,
		},
		{
			MethodName: "ResetWorld",
			Handler:    _Environment_ResetWorld_Handler,
		},
		{
			MethodName: "SpawnFood",
			Handler:    _Environment_SpawnFood_Handler,
		},
		{
			MethodName: "GetEntitiesInRegion",
			Handler:    _Environment_GetEntitiesInRegion_Handler,
		},
		{
			MethodName: "GetEffectsInRegion",
			Handler:    _Environment_GetEffectsInRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environment.proto",
}
