// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collective.proto

package endpoints_terrariumai_collective

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entity message that is in observations
type Entity struct {
	// Unique integer identifier of the agent
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Class id
	ClassID              uint32   `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetClassID() uint32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

type Cell struct {
	Occupant             *Entity  `protobuf:"bytes,1,opt,name=occupant,proto3" json:"occupant,omitempty"`
	Pheromone            uint32   `protobuf:"varint,2,opt,name=pheromone,proto3" json:"pheromone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{1}
}

func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (m *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(m, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetOccupant() *Entity {
	if m != nil {
		return m.Occupant
	}
	return nil
}

func (m *Cell) GetPheromone() uint32 {
	if m != nil {
		return m.Pheromone
	}
	return 0
}

// Observation is a list of cells around an agent
type Observation struct {
	// Is the agent alive
	IsAlive bool `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	// Energy
	Energy uint32 `protobuf:"varint,2,opt,name=energy,proto3" json:"energy,omitempty"`
	// Health
	Health uint32 `protobuf:"varint,3,opt,name=health,proto3" json:"health,omitempty"`
	// Id of the agent that is observing
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// List of cells around the agent
	Cells                []*Cell  `protobuf:"bytes,5,rep,name=cells,proto3" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Observation) Reset()         { *m = Observation{} }
func (m *Observation) String() string { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()    {}
func (*Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{2}
}

func (m *Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observation.Unmarshal(m, b)
}
func (m *Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observation.Marshal(b, m, deterministic)
}
func (m *Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observation.Merge(m, src)
}
func (m *Observation) XXX_Size() int {
	return xxx_messageInfo_Observation.Size(m)
}
func (m *Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_Observation proto.InternalMessageInfo

func (m *Observation) GetIsAlive() bool {
	if m != nil {
		return m.IsAlive
	}
	return false
}

func (m *Observation) GetEnergy() uint32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Observation) GetHealth() uint32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Observation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Observation) GetCells() []*Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

// Action is an action to be performed
type Action struct {
	// Id for the agent that should perform the action
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// identifier for the action
	// 0: WAIT
	// 1: MOVE
	// 2: EAT
	Action uint32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	// direction to perform the action in
	// 0: UP
	// 1: DOWN
	// 2: LEFT
	// 3: RIGHT
	Direction            uint32   `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Action) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *Action) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type ObservationPacket struct {
	// List of observations for every agent the RM is controlling
	Observations         []*Observation `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ObservationPacket) Reset()         { *m = ObservationPacket{} }
func (m *ObservationPacket) String() string { return proto.CompactTextString(m) }
func (*ObservationPacket) ProtoMessage()    {}
func (*ObservationPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{4}
}

func (m *ObservationPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObservationPacket.Unmarshal(m, b)
}
func (m *ObservationPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObservationPacket.Marshal(b, m, deterministic)
}
func (m *ObservationPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObservationPacket.Merge(m, src)
}
func (m *ObservationPacket) XXX_Size() int {
	return xxx_messageInfo_ObservationPacket.Size(m)
}
func (m *ObservationPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ObservationPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ObservationPacket proto.InternalMessageInfo

func (m *ObservationPacket) GetObservations() []*Observation {
	if m != nil {
		return m.Observations
	}
	return nil
}

// Request data to create new agent
type ActionPacket struct {
	// List of actions to be performed
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionPacket) Reset()         { *m = ActionPacket{} }
func (m *ActionPacket) String() string { return proto.CompactTextString(m) }
func (*ActionPacket) ProtoMessage()    {}
func (*ActionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c8c35156a1a162, []int{5}
}

func (m *ActionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionPacket.Unmarshal(m, b)
}
func (m *ActionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionPacket.Marshal(b, m, deterministic)
}
func (m *ActionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionPacket.Merge(m, src)
}
func (m *ActionPacket) XXX_Size() int {
	return xxx_messageInfo_ActionPacket.Size(m)
}
func (m *ActionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ActionPacket proto.InternalMessageInfo

func (m *ActionPacket) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "endpoints.terrariumai.collective.Entity")
	proto.RegisterType((*Cell)(nil), "endpoints.terrariumai.collective.Cell")
	proto.RegisterType((*Observation)(nil), "endpoints.terrariumai.collective.Observation")
	proto.RegisterType((*Action)(nil), "endpoints.terrariumai.collective.Action")
	proto.RegisterType((*ObservationPacket)(nil), "endpoints.terrariumai.collective.ObservationPacket")
	proto.RegisterType((*ActionPacket)(nil), "endpoints.terrariumai.collective.ActionPacket")
}

func init() { proto.RegisterFile("collective.proto", fileDescriptor_e2c8c35156a1a162) }

var fileDescriptor_e2c8c35156a1a162 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcb, 0x8e, 0xda, 0x30,
	0x14, 0xad, 0x79, 0x04, 0xb8, 0xd0, 0xaa, 0xf5, 0x02, 0x45, 0x55, 0x17, 0x51, 0x16, 0x55, 0x36,
	0x8d, 0xaa, 0xb0, 0xed, 0x86, 0x42, 0x17, 0x5d, 0xf4, 0xe5, 0x3f, 0x30, 0xce, 0xed, 0xe0, 0x19,
	0x63, 0x47, 0x8e, 0x41, 0x62, 0x35, 0x5f, 0x30, 0x9f, 0x31, 0xff, 0x39, 0x4a, 0x9c, 0x10, 0x66,
	0x36, 0x30, 0xcb, 0x73, 0x2e, 0xe7, 0x65, 0x14, 0x78, 0x2f, 0x8c, 0x52, 0x28, 0x9c, 0x3c, 0x60,
	0x5a, 0x58, 0xe3, 0x0c, 0x8d, 0x50, 0xe7, 0x85, 0x91, 0xda, 0x95, 0xa9, 0x43, 0x6b, 0xb9, 0x95,
	0xfb, 0x1d, 0x97, 0x69, 0xf7, 0xbb, 0x38, 0x83, 0xe0, 0x87, 0x76, 0xd2, 0x1d, 0xe9, 0x3b, 0xe8,
	0xc9, 0x3c, 0x24, 0x11, 0x49, 0x26, 0xac, 0x27, 0x73, 0x1a, 0xc2, 0x48, 0x28, 0x5e, 0x96, 0x3f,
	0xd7, 0x61, 0x2f, 0x22, 0xc9, 0x5b, 0xd6, 0xc2, 0xf8, 0x16, 0x06, 0x2b, 0x54, 0x8a, 0xae, 0x61,
	0x6c, 0x84, 0xd8, 0x17, 0x5c, 0xbb, 0x5a, 0x37, 0xcd, 0x92, 0xf4, 0x52, 0x60, 0xea, 0xd3, 0xd8,
	0x49, 0x49, 0x3f, 0xc1, 0xa4, 0xd8, 0xa2, 0x35, 0x3b, 0xa3, 0xb1, 0x49, 0xea, 0x88, 0xf8, 0x91,
	0xc0, 0xf4, 0xcf, 0xa6, 0x44, 0x7b, 0xe0, 0x4e, 0x1a, 0x5d, 0xb5, 0x92, 0xe5, 0x52, 0xc9, 0x03,
	0xd6, 0x91, 0x63, 0xd6, 0x42, 0x3a, 0x87, 0x00, 0x35, 0xda, 0x9b, 0x63, 0x63, 0xd2, 0xa0, 0x8a,
	0xdf, 0x22, 0x57, 0x6e, 0x1b, 0xf6, 0x3d, 0xef, 0x51, 0xb3, 0x77, 0x70, 0xda, 0xfb, 0x0d, 0x86,
	0x02, 0x95, 0x2a, 0xc3, 0x61, 0xd4, 0x4f, 0xa6, 0xd9, 0xe7, 0xcb, 0x53, 0xaa, 0x47, 0x60, 0x5e,
	0x14, 0xff, 0x86, 0x60, 0x29, 0xea, 0x86, 0x2f, 0xdf, 0x71, 0x0e, 0x01, 0xaf, 0x2f, 0x6d, 0x2f,
	0x8f, 0xaa, 0xdd, 0xb9, 0xb4, 0xe8, 0x4f, 0xbe, 0x5a, 0x47, 0xc4, 0xff, 0xe1, 0xc3, 0xd9, 0xec,
	0xbf, 0x5c, 0xdc, 0xa1, 0xa3, 0xff, 0x60, 0x66, 0x3a, 0xb2, 0x0c, 0x49, 0xdd, 0xf4, 0xcb, 0xe5,
	0xa6, 0x67, 0x56, 0xec, 0x99, 0x45, 0xcc, 0x60, 0xe6, 0x7b, 0x37, 0x11, 0xdf, 0x61, 0xe4, 0xfb,
	0xb5, 0xee, 0x57, 0xfc, 0xa5, 0xde, 0x80, 0xb5, 0xc2, 0xec, 0x81, 0x00, 0xac, 0x4e, 0x67, 0x7a,
	0x0f, 0x74, 0x65, 0xb4, 0x46, 0xe1, 0x18, 0xee, 0x8c, 0xc3, 0x5f, 0x26, 0x47, 0x45, 0xd3, 0x6b,
	0x7d, 0x7d, 0xb1, 0x8f, 0x8b, 0x57, 0xad, 0xf4, 0xa2, 0xf8, 0x4d, 0x42, 0xbe, 0x92, 0x4d, 0x50,
	0x7f, 0x0c, 0x8b, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xa6, 0x65, 0x7f, 0x20, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CollectiveClient is the client API for Collective service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectiveClient interface {
	// Connect a new RM
	ConnectRemoteModel(ctx context.Context, opts ...grpc.CallOption) (Collective_ConnectRemoteModelClient, error)
}

type collectiveClient struct {
	cc *grpc.ClientConn
}

func NewCollectiveClient(cc *grpc.ClientConn) CollectiveClient {
	return &collectiveClient{cc}
}

func (c *collectiveClient) ConnectRemoteModel(ctx context.Context, opts ...grpc.CallOption) (Collective_ConnectRemoteModelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Collective_serviceDesc.Streams[0], "/endpoints.terrariumai.collective.Collective/ConnectRemoteModel", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectiveConnectRemoteModelClient{stream}
	return x, nil
}

type Collective_ConnectRemoteModelClient interface {
	Send(*ActionPacket) error
	Recv() (*ObservationPacket, error)
	grpc.ClientStream
}

type collectiveConnectRemoteModelClient struct {
	grpc.ClientStream
}

func (x *collectiveConnectRemoteModelClient) Send(m *ActionPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectiveConnectRemoteModelClient) Recv() (*ObservationPacket, error) {
	m := new(ObservationPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectiveServer is the server API for Collective service.
type CollectiveServer interface {
	// Connect a new RM
	ConnectRemoteModel(Collective_ConnectRemoteModelServer) error
}

// UnimplementedCollectiveServer can be embedded to have forward compatible implementations.
type UnimplementedCollectiveServer struct {
}

func (*UnimplementedCollectiveServer) ConnectRemoteModel(srv Collective_ConnectRemoteModelServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectRemoteModel not implemented")
}

func RegisterCollectiveServer(s *grpc.Server, srv CollectiveServer) {
	s.RegisterService(&_Collective_serviceDesc, srv)
}

func _Collective_ConnectRemoteModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectiveServer).ConnectRemoteModel(&collectiveConnectRemoteModelServer{stream})
}

type Collective_ConnectRemoteModelServer interface {
	Send(*ObservationPacket) error
	Recv() (*ActionPacket, error)
	grpc.ServerStream
}

type collectiveConnectRemoteModelServer struct {
	grpc.ServerStream
}

func (x *collectiveConnectRemoteModelServer) Send(m *ObservationPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectiveConnectRemoteModelServer) Recv() (*ActionPacket, error) {
	m := new(ActionPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Collective_serviceDesc = grpc.ServiceDesc{
	ServiceName: "endpoints.terrariumai.collective.Collective",
	HandlerType: (*CollectiveServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectRemoteModel",
			Handler:       _Collective_ConnectRemoteModel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "collective.proto",
}
